version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v12:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Verify build
          command: echo "Build completed successfully!"
  test-v16:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "16.20"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Verify build
          command: echo "Build completed successfully!"
  test-v20:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "20.12"
      - run:
          name: Run build
          command: npm install
      - run:
          name: Verify build
          command: echo "Build completed successfully!"
workflows:
  build_and_test:
    jobs:
      - test-v12
      - test-v16
      - test-v20
